### ISSUE TITLE
Add a location

### ISSUE THREAD

**Issue by borjanpopovic** [borjanpopovic/capstone-project#1]
**Value statement:**

As a user I want to be able to enter all details, that are necessary to add a location to the list of locations. 

**Complexity:**
L

**Acceptance criteria:**  

- [x] User can enter the name, address(street, number, zip), category of a location and choose a pin icon for the map. 
- [x] By clicking the "Add to list/map" Button, the location is added to the location list.

**Tasks:**
- [x] Create the form in html/jsx with all 
inputfields and buttons.
- [x] Import all pin-icons and create the dropdown menu for them.
- [x] Write functions to add the location to the location list.

<img width="305" alt="Bildschirmfoto 2021-06-03 um 16 47 51" src="https://user-images.githubusercontent.com/82392602/120666609-03e98300-c48d-11eb-8373-1e7a5b408c21.png">
