### ISSUE TITLE
Connecting location entries + map pins to map

### ISSUE THREAD

**Issue by borjanpopovic** [borjanpopovic/capstone-project#10]
**Value statement:**

As a user I want to be able to see the map icon of all added locations on the map.

**Complexity:**
L

**Acceptance criteria:**  

- [x] By clicking the "Add to list/map" Button, the location is added to the map.

Optional: Alternatively to entering an adress, the user can click on a button which triggers the determination of the current position of the user to pin it with the chosen icon plus name/category to the map.

**Tasks:**

- [x] Write function to get the latitude/longitude of the current position.
- [x] Write function to add the location to the map at the position of the entered adress.
- [x] Write function to pin the location on the map with the chosen icon.

Optional:  Write function which pins the location to the map based on the determinated current position.
