### ISSUE TITLE
Filter/search bar for location list

### ISSUE THREAD

**Issue by borjanpopovic** [borjanpopovic/capstone-project#15]
**Value statement:**

As a user I want to be able to type in keywords in a search bar on the location list page so that I can find certain locations from the list easier.

**Complexity:**
L

**Acceptance criteria:**  

- [x] When the user types something in the search bar the location list adapts so only locations are visible which contain the sequence of letters that are entered in the search bar.  

**Tasks:**

- [x] Create a search bar on the location list page.
- [x] Write function that filters content of the location list according to the entries of the search bar.
