### ISSUE TITLE
App navigation

### ISSUE THREAD

**Issue by borjanpopovic** [borjanpopovic/capstone-project#2]
**Value statement:**

As a user I want to be able to navigate through the app so I can reach the single pages: Form, list and map.

**Complexity:**
M

**Acceptance criteria:** 

- [x] User can click on the three navigation icons to navigate to the chosen page.

**Tasks:**
- [x] Create new feature branch "navigation"
- [x] Create navigation bar with icon-buttons for the three pages of the app.
- [x] Make the navigation work by implementing declarative routing with React Router.
- [x] Add Styleguidist
- [x] Testing with Cypress

<img width="300" alt="Bildschirmfoto 2021-06-03 um 17 45 59" src="https://user-images.githubusercontent.com/82392602/120673589-98ef7a80-c493-11eb-86cc-5382b1c3792d.png">
