### ISSUE TITLE
Location list

### ISSUE THREAD

**Issue by borjanpopovic** [borjanpopovic/capstone-project#3]
**Value statement:**

As a user I want to have all the added locations in a list.

**Complexity:**
M

**Acceptance criteria:** 

- [x] The user can see all the added locations as cards in a list with their name, category, icon and adress plus a delete-button.

**Tasks:**

- [x] Write a function that renders a card for each added location.
- [x] Create a delete-button for the card component.

<img width="301" alt="Bildschirmfoto 2021-06-03 um 21 38 38" src="https://user-images.githubusercontent.com/82392602/120712468-f3eb9680-c4c0-11eb-9a83-e9a65b432bad.png">
