### ISSUE TITLE
Map

### ISSUE THREAD

**Issue by borjanpopovic** [borjanpopovic/capstone-project#4]
**Value statement:**

As a user I want to see the icons of the added locations on the map page of the app.

**Complexity:**
L

**Acceptance criteria:**  

- [x] User can scroll on a map and see the pinned icon of each added location.

**Tasks:**

- [x] Open up new branch "map"
- [x] Fetch and embed a map api
- [x] Create a function, that renders the icon of an added location to the appropriate position

<img width="299" alt="Bildschirmfoto 2021-06-03 um 23 33 11" src="https://user-images.githubusercontent.com/82392602/120714892-1c28c480-c4c4-11eb-90e0-99620d42613c.png">
 the map
