### ISSUE TITLE
Persist locations in list

### ISSUE THREAD

**Issue by borjanpopovic** [borjanpopovic/capstone-project#5]
**Value statement:**

As a user I want  all my added locations to be kept in the list so that I can see them when I reopen/reload the app.

**Complexity:**
M

**Acceptance criteria:** 

- [x] The user can see all added locations in the list after reloading/reopening/revisiting the app.
- [x]  The user doesn't have to explicitly save them. It is done automatically by adding them on the form page.

**Tasks:**

- [x] Write functions for the localstorage to save locations to localstorage and load them from localstorage when the locations array changes.
