### ISSUE TITLE
Persist locations/icons on map

### ISSUE THREAD

**Issue by borjanpopovic** [borjanpopovic/capstone-project#6]
**Value statement:**

As a user I want  all my added locations/pin icons to be kept on the map so that I can see them when I reopen/reload the app.

**Complexity:**
M

**Acceptance criteria:** 

- [x] The user can see all added locations/pin icons on the map after reloading/reopening/revisiting the app.
- [x]  The user doesn't have to explicitly save them. It is done automatically by adding them on the form page.

**Tasks:**

- [x] Write functions for the localstorage to save pin icons to localstorage and load them from localstorage when the pin icon array changes.
